Flowpack:
  SeoRouting:
    redirect:
      enable:
        trailingSlash: true
        toLowerCase: false
      trailingSlashMode: 'add'
      statusCode: 301
    blocklist:
      '/neos.*': true

Neos:
  Flow:
    http:
      middlewares:
        'after routing':
          middleware: 'Flowpack\SeoRouting\RoutingMiddleware'
